name: Test

on:
  repository_dispatch:
    types: [test-1, test-2]
  pull_request:
    types: [ready_for_review]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo Action: ${{ github.event.action }}
          echo Event type ${{ github.event.event_type }}
