name: Test

on:
  repository_dispatch:
    types: [test-1, test-2]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo ${{ github.event }}